# Configuration file for PSNextcloudUSB.
# if you have chosen "nano" as your editor, use Ctrl+X, then Y, then Enter to save and continue. If you have chosen something else, you probably don't need instructions. :p

# URL to nextcloud instance where to upload files to
url=http://example.org
# Ignore SSL errors (true/false)
ignore_certificates=false

# How to login to Nextcloud, this is either "password" or "token"
login_method=password
username=
password=
token=

# Directory to upload files to
upload_directory=PSNextcloudUSB

# Minimum level for log messages
loglevel=INFO

# Seconds to delay uploads to ensure files are complete
wait_time_sec=300

# Seconds between file system checks
check_time_sec=180

root_directory=/usbdisk.d
